### ISSUE TITLE
请问下app目录里的各个文件夹里面的mixin.js、model.js、router.js是怎样引用吗？

### ISSUE THREAD

**Issue by joket1999** [cheft/cheft#8]
基本有每一个功能页面都有mixin.js、model.js、router.js还有index.html。mixin.js在index.html通过app.mixin(this, require('./mixin'));执行。但是model.js、router.js是怎么引用的呢？能说明下吗？

**Comment by cheft** [comment]
model.js router.js 是后端的东西，在 lib/server.js 是通过轮询文件夹加载的。 前端模块是在 webpack 轮询的，原理一样。
